server:
  port: 8081


druid:
  url:  jdbc:sqlserver://192.168.3.99:1433;DatabaseName=TopDB
  driver-class-name:  com.microsoft.sqlserver.jdbc.SQLServerDriver
  username:  sa
  password:  top@qadb123
  initial-size:  10
  max-active:  50
  min-idle:  10
  max-wait:  60000
  pool-prepared-statements:  true
  max-pool-prepared-statement-per-connection-size:  20
  validation-query:  SELECT 1
  test-on-borrow:  false
  test-on-return:  false
  test-while-idle:  true
  time-between-eviction-runs-millis:  60000
  filters:  stat,wall


key:
  keyFileName: cgo.keystore
  pwd: cgopwd
  storePwd: cgostorepwd
  alias: cgo